# Generated by Django 6.0.5 on 2026-05-31 22:19

from django.db import migrations, models


def approve_existing_coaches(apps, schema_editor):
    Coach = apps.get_model('gym', 'Coach')
    for coach in Coach.objects.all():
        updates = []
        if coach.is_active:
            coach.approval_status = 'APPROVED'
            coach.otp_verified = True
            updates.extend(['approval_status', 'otp_verified'])
        if coach.phone and not coach.phone_number:
            coach.phone_number = coach.phone
            updates.append('phone_number')
        if updates:
            coach.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_product_accessscan_coachbonus_notification_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuve'), ('REJECTED', 'Rejete')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='coach',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='coach',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coach',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RunPython(approve_existing_coaches, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='coach',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
