# Generated by Django 6.0.5 on 2026-05-31 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_coach_approval_status_coach_otp_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='otp_expires_at',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='otp_verified',
        ),
    ]
